version: '3'

services:
  node_app:
    container_name: node_fmecg
    build: .
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - .:/app
    depends_on:
      - database
      - phpmyadmin
    env_file: config.env
    networks:
      - internal

  database:
    image: mysql:8.0
    container_name: database_fmecg
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: fm_ecg
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql:/data
    networks:
      - internal

  phpmyadmin:
    container_name: phpadmin_fmecg
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80
    expose:
      - 8080
    environment:
      PMA_HOST: database # host is a name of mysql service in docker compose
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/phpadmin:/data/:cached
    networks:
      - internal

networks:
  internal:
    driver: bridge
