name: Automatic build and push images to Docker
on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./server-web/Dockerfile
            image: thaidmfinnick/fmecg-node-app
          - dockerfile: ./frontend_web/Dockerfile
            image: thaidmfinnick/fmecg-react-app
          - dockerfile: ./frontend_web/bin/Dockerfile
            image: thaidmfinnick/fmecg-bin-login
          - dockerfile: ./proxy/Dockerfile
            image: thaidmfinnick/fmecg-proxy
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:latest
  
  run-docker-images:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/finnick/fmECG_docker
          make app
