name: CI/CD for Mobile App
on: 
  push:
    branches: 
      - feature/add_cicd
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.9"
        channel: stable
        cache: true
    - name: Check Flutter version
      run: flutter --version

    - name: Install dependencies 
      run: cd mobile_app && flutter pub get
    # - name: Run test
    #   run: flutter test --coverage
    - name: Build APK
      run: cd mobile_app && flutter build apk --no-shrink --no-tree-shake-icons
    - name: Create a Release APK
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "mobile_app/build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}